version: "3.8"
services:
  jobmanager:
    image: flink:1.12.3-scala_2.11
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:1.12.3-scala_2.11
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2

  jobserver:
    image: apache/beam_flink1.12_job_server:2.30.0
    depends_on:
      - taskmanager
    command: ["--artifacts-dir", "/opt/artifacts"]
    volumes:
      - ./data/artifacts:/opt/artifacts
    network_mode: host

  python_sdk:
    image: apache/beam_python3.7_sdk:2.30.0
    depends_on:
      - jobserver
    command: --worker_pool
    network_mode: host
